cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/Gruntfile.js .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/LICENSE .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/README.md .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/bower.json .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/css .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/demo.html .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/draft .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/fig .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/figures .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/index.html .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/js .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/kamoulox.bib .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/killport .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/lib .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/mathieu.html .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/node_modules .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/npm-debug.log .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/package-lock.json .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/package.json .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/plugin .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/start.sh .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/team_meeting.html .
cp -r /home/ssivasan/Dropbox/sunit_inria/phd/thesis/SunitThesis/presentation/test .
